#docker-compose.yml
version: "3.5"


services:
  postgres_db:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5434:${DB_PORT}"
    volumes: [ './postgres/db/:/var/lib/postgresql/data/', './postgres/db/:/logs/' ]
    command: ["postgres", "-c", "log_statement=all"]
    expose:
      - 5434
    networks:
      market_place_network:
        ipv4_address: 192.168.55.4

  django:
    depends_on:
      - postgres_db
    build: .
    container_name: django
    command: bash -c "
      python manage.py migrate
      && python manage.py 1_add_superuser
      && python manage.py 2_add_status_order
      && gunicorn market_place.wsgi:application --bind "0.0.0.0:8080" --workers 3
      "
    volumes: [ './market_place/market_place/templates/static/media/:/market_place/market_place/templates/static/media']
#    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      market_place_network:
        ipv4_address: 192.168.55.5

networks:
  market_place_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1
