  #docker-compose.yml
version: "3"


services:
  postgres_db:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5434:${DB_PORT}"
    volumes: [ './postgres/db/:/var/lib/postgresql/data/', './postgres/db/:/logs/' ]
    command: ["postgres", "-c", "log_statement=all"]
    expose:
      - 5434
    networks:
      advertising_services_network:
        ipv4_address: 192.168.55.4

#  django:
#    depends_on:
#      - postgres_db
#    build: .
#    container_name: django
#    command: bash -c "
#      python manage.py migrate
#      && gunicorn market_place.wsgi:application --bind "0.0.0.0:8080" --workers 3
#      "
##    volumes: [ './django_crm/uploads/:/app/uploads']
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    networks:
#      advertising_services_network:
#        ipv4_address: 192.168.55.5

#  localxpose:
#    depends_on:
#      - django
#    image: localxpose/localxpose:latest # read more here https://hub.docker.com/r/localxpose/localxpose
#    # forward any incoming requests to traefik container
#    command: tunnel -r http --reserved-domain "*.example.com" --to 0.0.0.0:8080
#    environment:
#      # Get your access token from your dashboard here https://localxpose.io/dashboard/access
#      ACCESS_TOKEN: pYTRGmfzMTnlKy7eJ1UDB3Hl8XPAHXwGn86fUD3I
#    networks:
#      advertising_services_network:
#        ipv4_address: 192.168.55.6

networks:
  advertising_services_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1
