# Generated by Django 5.1.2 on 2024-10-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0004_remove_basket_quantity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Basket",
        ),
    ]
