# Generated by Django 5.1.2 on 2024-10-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0003_profile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
