# Generated by Django 5.1.2 on 2024-10-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
