# Generated by Django 5.1.2 on 2024-10-21 04:53

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_product_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=shop.models.prod_photo_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="group",
            field=models.ManyToManyField(related_name="products", to="shop.group"),
        ),
    ]
