# Generated by Django 5.1.2 on 2024-10-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_photo_alter_product_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(default=20, max_length=5),
            preserve_default=False,
        ),
    ]
