# Generated by Django 5.1.2 on 2024-10-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
