# Generated by Django 5.1.2 on 2024-10-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_product_color_alter_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_for_url",
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="name_for_url",
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
