# Generated by Django 5.1.2 on 2024-10-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_category_name_for_url_group_name_for_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name_for_url",
            field=models.CharField(max_length=50),
        ),
    ]
