# Generated by Django 5.1.2 on 2024-10-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_category_name_for_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="name_for_url",
        ),
        migrations.RemoveField(
            model_name="group",
            name="name_for_url",
        ),
    ]
