# Generated by Django 5.1.2 on 2024-10-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_category_name_for_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount",
        ),
    ]
