# Generated by Django 5.1.2 on 2024-10-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="group",
            field=models.ManyToManyField(to="product.group"),
        ),
    ]
