# Generated by Django 5.1.2 on 2024-10-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_order_products_remove_order_promocode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.TextField(blank=True),
        ),
    ]
