# Generated by Django 5.1.2 on 2024-10-31 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="price",
            new_name="total_price",
        ),
    ]
